apiVersion: v1
kind: PersistentVolume
metadata:
  name: busybox-pv
  labels:
    app: busybox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # ReadWriteOnce, ReadWriteMany, ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain # Retain, Recycle, Delete
  storageClassName: local-path # Standard longhorn, nfs-client, local-path, etc
  hostPath:
    path: /pv-data   # replace with your actual host path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: busybox-pvc
