apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: alpine
          command:
            - sh
            - -c
            - |
              echo "Job started at $(date)"
              echo "Running some work..."
              sleep 5
              echo "Computing something..."
              echo "1 + 1 = 2"
              echo "Job finished at $(date)"
  backoffLimit: 3
